apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo Rollouts Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: argo-rollouts
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true