apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: External DNS Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: external-dns
    server: '*'
  - namespace: kube-system
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true